PYTHON = python3

style-transfer : style-transfer.py
	$(PYTHON) style-transfer.py images/cat.png images/style1.png cat_style1
	$(PYTHON) style-transfer.py images/cat.png images/style2.png cat_style2
	$(PYTHON) style-transfer.py images/cat.png images/style3.png cat_style3
	$(PYTHON) style-transfer.py images/cat.png images/style4.png cat_style4
	$(PYTHON) style-transfer.py images/cat.png images/style5.png cat_style5
	$(PYTHON) style-transfer.py images/cat.png images/style6.png cat_style6
	$(PYTHON) style-transfer.py images/city.png images/style1.png city_style1
	$(PYTHON) style-transfer.py images/city.png images/style2.png city_style2
	$(PYTHON) style-transfer.py images/city.png images/style3.png city_style3
	$(PYTHON) style-transfer.py images/city.png images/style4.png city_style4
	$(PYTHON) style-transfer.py images/city.png images/style5.png city_style5
	$(PYTHON) style-transfer.py images/city.png images/style6.png city_style6
	$(PYTHON) style-transfer.py images/milk.png images/style1.png milk_style1
	$(PYTHON) style-transfer.py images/milk.png images/style2.png milk_style2
	$(PYTHON) style-transfer.py images/milk.png images/style3.png milk_style3
	$(PYTHON) style-transfer.py images/milk.png images/style4.png milk_style4
	$(PYTHON) style-transfer.py images/milk.png images/style5.png milk_style5
	$(PYTHON) style-transfer.py images/milk.png images/style6.png milk_style6
	$(PYTHON) style-transfer.py images/noe.png images/style1.png noe_style1
	$(PYTHON) style-transfer.py images/noe.png images/style2.png noe_style2
	$(PYTHON) style-transfer.py images/noe.png images/style3.png noe_style3
	$(PYTHON) style-transfer.py images/noe.png images/style4.png noe_style4
	$(PYTHON) style-transfer.py images/noe.png images/style5.png noe_style5
	$(PYTHON) style-transfer.py images/noe.png images/style6.png noe_style6

